#ifndef __HEADER_H__
#define __HEADER_H__

/* Please don't insert anything in the middle of these
 * definitions or in snippets.h unless you know what
 * are you doing. It is safe to insert at the end.
 * */

#define RINDX_1_B_R RINDX_READ(1, to_byte, to_byte)
#define RINDX_1_W_R RINDX_READ(1, to_word, to_word)
#define RINDX_1_L_R RINDX_READ(1, to_long, to_double)
#define RINDX_2_B_R RINDX_READ(2, to_byte, to_byte)
#define RINDX_2_W_R RINDX_READ(2, to_word, to_word)
#define RINDX_2_L_R RINDX_READ(2, to_long, to_double)
#define RINDX_4_B_R RINDX_READ(4, to_byte, to_byte)
#define RINDX_4_W_R RINDX_READ(4, to_word, to_word)
#define RINDX_4_L_R RINDX_READ(4, to_long, to_double)
#define RINDX_8_B_R RINDX_READ(8, to_byte, to_byte)
#define RINDX_8_W_R RINDX_READ(8, to_word, to_word)
#define RINDX_8_L_R RINDX_READ(8, to_long, to_double)
#define REMAP_1_B_R REMAP_READ(1, to_byte, to_byte)
#define REMAP_1_W_R REMAP_READ(1, to_word, to_word)
#define REMAP_1_L_R REMAP_READ(1, to_long, to_double)
#define REMAP_2_B_R REMAP_READ(2, to_byte, to_byte)
#define REMAP_2_W_R REMAP_READ(2, to_word, to_word)
#define REMAP_2_L_R REMAP_READ(2, to_long, to_double)
#define REMAP_4_B_R REMAP_READ(4, to_byte, to_byte)
#define REMAP_4_W_R REMAP_READ(4, to_word, to_word)
#define REMAP_4_L_R REMAP_READ(4, to_long, to_double)
#define REMAP_8_B_R REMAP_READ(8, to_byte, to_byte)
#define REMAP_8_W_R REMAP_READ(8, to_word, to_word)
#define REMAP_8_L_R REMAP_READ(8, to_long, to_double)

#define RINDX_1_B_W RINDX_WRITE(1, to_byte, to_byte)
#define RINDX_1_W_W RINDX_WRITE(1, to_word, to_word)
#define RINDX_1_L_W RINDX_WRITE(1, to_long, to_double)
#define RINDX_2_B_W RINDX_WRITE(2, to_byte, to_byte)
#define RINDX_2_W_W RINDX_WRITE(2, to_word, to_word)
#define RINDX_2_L_W RINDX_WRITE(2, to_long, to_double)
#define RINDX_4_B_W RINDX_WRITE(4, to_byte, to_byte)
#define RINDX_4_W_W RINDX_WRITE(4, to_word, to_word)
#define RINDX_4_L_W RINDX_WRITE(4, to_long, to_double)
#define RINDX_8_B_W RINDX_WRITE(8, to_byte, to_byte)
#define RINDX_8_W_W RINDX_WRITE(8, to_word, to_word)
#define RINDX_8_L_W RINDX_WRITE(8, to_long, to_double)
#define REMAP_1_B_W REMAP_WRITE(1, to_byte, to_byte)
#define REMAP_1_W_W REMAP_WRITE(1, to_word, to_word)
#define REMAP_1_L_W REMAP_WRITE(1, to_long, to_double)
#define REMAP_2_B_W REMAP_WRITE(2, to_byte, to_byte)
#define REMAP_2_W_W REMAP_WRITE(2, to_word, to_word)
#define REMAP_2_L_W REMAP_WRITE(2, to_long, to_double)
#define REMAP_4_B_W REMAP_WRITE(4, to_byte, to_byte)
#define REMAP_4_W_W REMAP_WRITE(4, to_word, to_word)
#define REMAP_4_L_W REMAP_WRITE(4, to_long, to_double)
#define REMAP_8_B_W REMAP_WRITE(8, to_byte, to_byte)
#define REMAP_8_W_W REMAP_WRITE(8, to_word, to_word)
#define REMAP_8_L_W REMAP_WRITE(8, to_long, to_double)

#define RBASE_B_R RBASE_READ(to_byte, to_byte)
#define RBASE_W_R RBASE_READ(to_word, to_word)
#define RBASE_L_R RBASE_READ(to_long, to_double)
#define RDISP_B_R RDISP_READ(to_byte, to_byte)
#define RDISP_W_R RDISP_READ(to_word, to_word)
#define RDISP_L_R RDISP_READ(to_long, to_double)

#define RBASE_B_W RBASE_WRITE(to_byte, to_byte)
#define RBASE_W_W RBASE_WRITE(to_word, to_word)
#define RBASE_L_W RBASE_WRITE(to_long, to_double)
#define RDISP_B_W RDISP_WRITE(to_byte, to_byte)
#define RDISP_W_W RDISP_WRITE(to_word, to_word)
#define RDISP_L_W RDISP_WRITE(to_long, to_double)

#define MOVS_B EMULATE_MOVS(to_byte, to_byte)
#define MOVS_W EMULATE_MOVS(to_word, to_word)
#define MOVS_L EMULATE_MOVS(to_long, to_double)
#define STOS_B EMULATE_STOS(to_byte, to_byte)
#define STOS_W EMULATE_STOS(to_word, to_word)
#define STOS_L EMULATE_STOS(to_long, to_double)
#define SCAS_B EMULATE_SCAS(to_byte, to_byte)
#define SCAS_W EMULATE_SCAS(to_word, to_word)
#define SCAS_L EMULATE_SCAS(to_long, to_double)
#define CMPS_B EMULATE_CMPS(to_byte, to_byte)
#define CMPS_W EMULATE_CMPS(to_word, to_word)
#define CMPS_L EMULATE_CMPS(to_long, to_double)

#define RINDX_SAFE_1_B_R RINDXS_READ(1, to_byte, to_byte)
#define RINDX_SAFE_1_W_R RINDXS_READ(1, to_word, to_word)
#define RINDX_SAFE_1_L_R RINDXS_READ(1, to_long, to_double)
#define RINDX_SAFE_2_B_R RINDXS_READ(2, to_byte, to_byte)
#define RINDX_SAFE_2_W_R RINDXS_READ(2, to_word, to_word)
#define RINDX_SAFE_2_L_R RINDXS_READ(2, to_long, to_double)
#define RINDX_SAFE_4_B_R RINDXS_READ(4, to_byte, to_byte)
#define RINDX_SAFE_4_W_R RINDXS_READ(4, to_word, to_word)
#define RINDX_SAFE_4_L_R RINDXS_READ(4, to_long, to_double)
#define RINDX_SAFE_8_B_R RINDXS_READ(8, to_byte, to_byte)
#define RINDX_SAFE_8_W_R RINDXS_READ(8, to_word, to_word)
#define RINDX_SAFE_8_L_R RINDXS_READ(8, to_long, to_double)
#define REMAP_SAFE_1_B_R REMAPS_READ(1, to_byte, to_byte)
#define REMAP_SAFE_1_W_R REMAPS_READ(1, to_word, to_word)
#define REMAP_SAFE_1_L_R REMAPS_READ(1, to_long, to_double)
#define REMAP_SAFE_2_B_R REMAPS_READ(2, to_byte, to_byte)
#define REMAP_SAFE_2_W_R REMAPS_READ(2, to_word, to_word)
#define REMAP_SAFE_2_L_R REMAPS_READ(2, to_long, to_double)
#define REMAP_SAFE_4_B_R REMAPS_READ(4, to_byte, to_byte)
#define REMAP_SAFE_4_W_R REMAPS_READ(4, to_word, to_word)
#define REMAP_SAFE_4_L_R REMAPS_READ(4, to_long, to_double)
#define REMAP_SAFE_8_B_R REMAPS_READ(8, to_byte, to_byte)
#define REMAP_SAFE_8_W_R REMAPS_READ(8, to_word, to_word)
#define REMAP_SAFE_8_L_R REMAPS_READ(8, to_long, to_double)

#define RINDX_SAFE_1_B_W RINDXS_WRITE(1, to_byte, to_byte)
#define RINDX_SAFE_1_W_W RINDXS_WRITE(1, to_word, to_word)
#define RINDX_SAFE_1_L_W RINDXS_WRITE(1, to_long, to_double)
#define RINDX_SAFE_2_B_W RINDXS_WRITE(2, to_byte, to_byte)
#define RINDX_SAFE_2_W_W RINDXS_WRITE(2, to_word, to_word)
#define RINDX_SAFE_2_L_W RINDXS_WRITE(2, to_long, to_double)
#define RINDX_SAFE_4_B_W RINDXS_WRITE(4, to_byte, to_byte)
#define RINDX_SAFE_4_W_W RINDXS_WRITE(4, to_word, to_word)
#define RINDX_SAFE_4_L_W RINDXS_WRITE(4, to_long, to_double)
#define RINDX_SAFE_8_B_W RINDXS_WRITE(8, to_byte, to_byte)
#define RINDX_SAFE_8_W_W RINDXS_WRITE(8, to_word, to_word)
#define RINDX_SAFE_8_L_W RINDXS_WRITE(8, to_long, to_double)
#define REMAP_SAFE_1_B_W REMAPS_WRITE(1, to_byte, to_byte)
#define REMAP_SAFE_1_W_W REMAPS_WRITE(1, to_word, to_word)
#define REMAP_SAFE_1_L_W REMAPS_WRITE(1, to_long, to_double)
#define REMAP_SAFE_2_B_W REMAPS_WRITE(2, to_byte, to_byte)
#define REMAP_SAFE_2_W_W REMAPS_WRITE(2, to_word, to_word)
#define REMAP_SAFE_2_L_W REMAPS_WRITE(2, to_long, to_double)
#define REMAP_SAFE_4_B_W REMAPS_WRITE(4, to_byte, to_byte)
#define REMAP_SAFE_4_W_W REMAPS_WRITE(4, to_word, to_word)
#define REMAP_SAFE_4_L_W REMAPS_WRITE(4, to_long, to_double)
#define REMAP_SAFE_8_B_W REMAPS_WRITE(8, to_byte, to_byte)
#define REMAP_SAFE_8_W_W REMAPS_WRITE(8, to_word, to_word)
#define REMAP_SAFE_8_L_W REMAPS_WRITE(8, to_long, to_double)

#define RBASE_SAFE_B_R RBASES_READ(to_byte, to_byte)
#define RBASE_SAFE_W_R RBASES_READ(to_word, to_word)
#define RBASE_SAFE_L_R RBASES_READ(to_long, to_double)
#define RDISP_SAFE_B_R RDISPS_READ(to_byte, to_byte)
#define RDISP_SAFE_W_R RDISPS_READ(to_word, to_word)
#define RDISP_SAFE_L_R RDISPS_READ(to_long, to_double)

#define RBASE_SAFE_B_W RBASES_WRITE(to_byte, to_byte)
#define RBASE_SAFE_W_W RBASES_WRITE(to_word, to_word)
#define RBASE_SAFE_L_W RBASES_WRITE(to_long, to_double)
#define RDISP_SAFE_B_W RDISPS_WRITE(to_byte, to_byte)
#define RDISP_SAFE_W_W RDISPS_WRITE(to_word, to_word)
#define RDISP_SAFE_L_W RDISPS_WRITE(to_long, to_double)

#define MOVSS_B EMULATE_MOVSS(to_byte, to_byte)
#define MOVSS_W EMULATE_MOVSS(to_word, to_word)
#define MOVSS_L EMULATE_MOVSS(to_long, to_double)
#define STOSS_B EMULATE_STOSS(to_byte, to_byte)
#define STOSS_W EMULATE_STOSS(to_word, to_word)
#define STOSS_L EMULATE_STOSS(to_long, to_double)
#define SCASS_B EMULATE_SCASS(to_byte, to_byte)
#define SCASS_W EMULATE_SCASS(to_word, to_word)
#define SCASS_L EMULATE_SCASS(to_long, to_double)
#define CMPSS_B EMULATE_CMPSS(to_byte, to_byte)
#define CMPSS_W EMULATE_CMPSS(to_word, to_word)
#define CMPSS_L EMULATE_CMPSS(to_long, to_double)

#endif
